### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by slandelle** [shawjef3/digitalocean#6]
Hi @shawjef3,

It would be great if you could be so kind as to release for Scala 2.13.

Thanks!

**Comment by shawjef3** [comment]
Unit tests fail now, so I'll have to fix them and then I'll release for all versions.

**Comment by slandelle** [comment]
Cool! I don't have my DO token here, but I'll give it a try next week. Might also be worth upgrading AHC to latest release.

**Comment by shawjef3** [comment]
Yep. Definitely I'm taking the chance to upgrade dependencies.

**Comment by shawjef3** [comment]
Done!

**Comment by slandelle** [comment]
Thanks!
